### PR TITLE
fix top menu visibility for small screens

### PR DESCRIPTION
**Pull request by dawidmalina**
closes: https://github.com/erwindon/SaltGUI/issues/176

### CODE REVIEW

**Comment by dawidmalina** [comment]
@erwindon can you propose something - I'm out of ideas - it's look differently on different browsers.

**Comment by erwindon** [comment]
The best solution is to treat "hamburger" as a proper toplevel menu in the sequence minions, keys, jobs, logout. Stop switching between 2 separate block "mainmenubar" and "mainmenumini". Remove the code from `page.js` where it initializes the menu. Expand the menu highlighting with highlighting in the hamburgermenu for consistency.
I'm almost done with the coding for this...

**Comment by erwindon** [comment]
@dawidmalina can you please test the new solution for the menus?
bonus: the hamburger main menu now has exactly the same structure as the regular main menu.
it was a bit quick+dirty, so you may want to make some additional changes...

**Comment by dawidmalina** [comment]
@erwindon - now it's always displayed properly :)

**Comment by erwindon** [comment]
please indicate when it is ready for merge, or that you want to make additional changes

**Comment by dawidmalina** [comment]
LGTM :+1:

**Pull request merged**
