### PR TITLE
Webpack PART 5, requires PARTS: 1, 2, 3, 4

### LINKED ISSUE #72: Use javascript modules
I came across this article: https://developers.google.com/web/fundamentals/primers/modules
Could be something useful for SaltGUI (instead of `window.x` hacks to define global functions)
Specifically:
* utils.js:
`window.elapsedToString = function(date) {`
* utils.js:
`window.createElement = function(type, className, content) {`
* utils.js:
`window.escape = function(input) {`
* utils.js:
`window.makeTargetText = function(targetType, targetPattern) {`
* parsecmdline.js:
`window.parseCommandLine = function(toRun, args, params) {`

### PR DESCRIPTION
**Pull request by smarletta**
closes #72

### CODE REVIEW

**Comment by smarletta** [comment]
Seems that tests are not covering those parts ;-) will fix it

Erwin Dondorp <notifications@github.com> schrieb am Sa., 9. März 2019,
10:29:

**Comment by erwindon** [comment]
rebased this branch
fixed some missing imports
updated a legacy construction to match the new code

**Comment by erwindon** [comment]
I'm not impressed by `webpack`.
It forces to use a build procedure that we previously did not have, otherwise we still ship the old packed code. And the benefit is very low for a project as small as this one.
On the other hand, the updates to the modularization are great.
I'm thinking of removing the `webpack` code from this PR.
@smarletta @dawidmalina Any objections / agreement / remarks ?

**Comment by dawidmalina** [comment]
I don't know what are the benefits of all this changes as I'm not too good it this area. If this the proper way it should be done then ok if not what we will gain having it?

**Comment by smarletta** [comment]
Would keep webpack. As maybe the application will grow...

Later we could switch to typescript to have a more powerful language.

If you won't have that in the original project, no problem so I will
continue on my fork. In general I would like to bring in more functionality.

How are your plans for the Saltui project?

Erwin Dondorp <notifications@github.com> schrieb am Fr., 22. März 2019,
08:39:

**Comment by erwindon** [comment]
> dawidmalina: "I don't know what are the benefits of all this changes"
> smarletta: "Would keep webpack. As maybe the application will grow... [...] no problem so I will continue on my fork."

These are not must-have answers. The goal of SaltGUI has always been to be simple to maintain and use. I'll not merge the webpack part now.

**Comment by erwindon** [comment]
> smarletta: In general I would like to bring in more functionality.

That is more than welcome. We prefer functionality that will actually be used over functionality that is just technically possible or for demonstration. I'm looking forward to your proposal(s) in the issues section, or even PRs in its section.

**Comment by erwindon** [comment]
@dawidmalina 
Dawid, I've taken the modularization code from this PR and put that on my branch `modules`. Can you please take a quick look whether all functionality still works?

**Comment by erwindon** [comment]
@dawidmalina I found that the unit tests are not working anymore (my branch `modules`). do you have any hints?

**Comment by dawidmalina** [comment]
I'm not expert in this area so I don't know why it's not working. I have very tough week so I can't work on this now. It's very likely I would be able to check this in the coming week.

**Comment by erwindon** [comment]
Relax! That's the same error I have. Since last night I'm using `babel` to translate ES-with-modules to ES-without-modules. That looks promising. Just need to invoke the tests in the transformed code...

**Comment by dawidmalina** [comment]
Change needed to be able to run tests (tests are failing but it's a different story):
- package.json
```
@@ -5,6 +5,9 @@
   "version": "0.0.1",
   "license": "MIT",
   "devDependencies": {
+    "@babel/core": "^7.4.0",
+    "@babel/preset-env": "^7.4.2",
+    "@babel/register": "^7.4.0",
     "chai": "^4.1.2",
     "eslint": "^5.3.0",
     "mocha": "^5.2.0",
@@ -24,12 +27,26 @@
       "no-undef": 0,
       "no-unused-vars": 0,
       "no-console": 0,
-      "indent": ["error", 2],
+      "indent": [
+        "error",
+        2
+      ],
       "no-irregular-whitespace": 2,
       "no-whitespace-before-property": 2,
-      "no-multiple-empty-lines": ["error", { "max": 2, "maxEOF": 1 }],
+      "no-multiple-empty-lines": [
+        "error",
+        {
+          "max": 2,
+          "maxEOF": 1
+        }
+      ],
       "no-useless-escape": 0,
-      "no-constant-condition": ["error", { "checkLoops": false }],
+      "no-constant-condition": [
+        "error",
+        {
+          "checkLoops": false
+        }
+      ],
       "no-var": 2,
       "prefer-const": 2
     }
@@ -41,7 +58,7 @@
     "jslint": "eslint saltgui/static/scripts tests/",
     "stylelint": "stylelint 'saltgui/static/stylesheets/*.css'",
     "wait-for-docker": "node tests/helpers/wait-for-docker.js",
-    "test:unit": "mocha --trace-warnings --check-leaks --reporter spec tests/unit/",
+    "test:unit": "mocha --require @babel/register --trace-warnings --check-leaks --reporter spec tests/unit/",
     "test:functional": "mocha --trace-warnings --check-leaks --reporter spec tests/functional/"
   }
 }
```
> Formatting is not required but it's always done by npm

- .babelrc
```
{
  "presets": [ "@babel/preset-env" ]
}
```

Special thanks for @rictariman for the help with solving this problem 👍

**Comment by erwindon** [comment]
👍 👍 I have something similar, also using babel, but much more complicated. all the unit tests work though. Seems I just have to pick the best of both worlds! thx @rictariman for for helping out!

**Comment by erwindon** [comment]
The last error was due to a parameter that was removed with the introduction of modules. But the parameter was still present in the unit tests...
My solution had 10 times the number of changed lines (don't tell anyone). I replaced it with the above code.

**Comment by erwindon** [comment]
The new code replaced my code on the same branch `modules`. The unit tests now all succeed.
Is there anything that we can do to improve the functional tests now also?

**Comment by erwindon** [comment]
merged `modules` with main branch

**Pull request closed without merging**
