### PR TITLE
feature request: keyboard shortcuts, ESC key

### PR DESCRIPTION
**Pull request by erwindon**
In addition to clicking to [X] on the Manual Run modal window, it would be great to have the same effect by pressing the ESC key. Also, on the main page, some keyboard shortcuts could make tasks easier. For example:

- "r" for opening the Manual Run modal
- "m" for minions
- ...and so on.
- "t" for templates. on this page, "1", "2", "3" etc. could apply the relevant template

### CODE REVIEW

**Comment by erwindon** [comment]
turned issue into PR

**Comment by erwindon** [comment]
first change is a general improvement.
hiding a useless column had some issues, that is now fixed.
first (and so far only) column to hide was the "Category" column for the templates overview

**Comment by erwindon** [comment]
second change is to allow assignment of a key to a template.
any regular key can be bound to a template by adding the property "key" to the original template definition, e.g. `key: "7"`.
note that alphabetic keys will be used in the near future to select regular menu-items (to switch to a specific page).
pressing the key will open the command-box and fill it with the values from the associated template.
this can be initiated from any page as long a no other input-control has the focus (should only happen with the 2 fields of the CommandBox and the radio-buttons on the Options page)

**Comment by erwindon** [comment]
feel free to install the software from the branch and try it...

**Comment by ZsBT** [comment]
I've tested it thoroughly and did not found any issues. It works from any page as expected, even on the Manual Run modal window ;)
Maybe a hint on the Manual Run hamburger menu could be useful, but it's not important as shortcut keys can be seen on the Templates page.

manualrun-template

I am thinking of something like Reload HAproxies [3] , Reload Nagios [7] , in my case.

All in all, it works great, thanks for the implementation.

**Comment by erwindon** [comment]
> I've tested it thoroughly and did not found any issues.

thx!

> It works from any page as expected, even on the Manual Run modal window ;)

I noticed that too, but found no reason to take the extra effort to prevent it.

> Maybe a hint on the Manual Run hamburger menu could be useful, but it's not important as shortcut keys can be seen on the Templates page.

good point. can do that.

> [menu-bar keys]

will be working on that after the previous one.

**Comment by erwindon** [comment]
just added the display of the shortcut in the templates menu.

**Comment by erwindon** [comment]
added page navigation by using first character of function-name.
"c" opens the command-box.
now working on making that more visible.

**Comment by erwindon** [comment]
added highlight of first menu-item character in the main menu
works completely in the wide-screen edition of the main menu
only works for the major menu-items in the small-screen edition of the main menu
also nothing for the `>_` button yet

**Comment by ZsBT** [comment]
I've just tried this branch. For me, the navigation is lightning-fast, I could not find any bugs.

**Comment by erwindon** [comment]
thx again for testing!

> only works for the major menu-items in the small-screen edition of the main menu

that is the only remaining work for now: to get the keyboard shortcut working for all main-menu-items in the small-screen edition...

**Comment by erwindon** [comment]
I've added the code to show the keyboard indicators.
this concludes the set of changes.
can you please do one final test?
note that I've used `git push --force` on code that you already have to fix a cosmetic issue. I suggest `git pull -r` to update.

**Comment by ZsBT** [comment]
Tested again and all works as expected. Thanks!

**Pull request merged**
