### PR TITLE
support multiple output formats

### PR DESCRIPTION
**Pull request by erwindon**
Update to support more output formats.
* Output is configurable through the `master` file.
* The current (default) configuration is `doc` + `highstate` + `json`.
* `doc` formats documentation output, also selecting the output of one minion (existing functionality)
* `highstate` formats highstate output, also sorting it (existing functionality).
* `doc` and `highstate` are only active when the output can be identified as such.
* Other supported outputs are `yaml` and `nested`. Specifying more than one from `[json,yaml,nested]` is useless since these can always be applied.
* Unit tests are added for yaml/nested.
* Note that generic syntax colouring is not added.

Note that this PR is not complete yet...

### CODE REVIEW

**Comment by dawidmalina** [comment]
Looks really nice. But would you consider to remove empty list and string for nested output (indent would be nice as well)?
```
domain:
''
ip4_nameservers:
- 127.0.0.11
ip6_nameservers:
[ ]
nameservers:
- 127.0.0.11
options:
- ndots:0
search:
[ ]
sortlist:
[ ]
```
to have this:
```
    dns:
        ----------
        domain:
        ip4_nameservers:
            - 127.0.0.11
        ip6_nameservers:
        nameservers:
            - 127.0.0.11
        options:
            - ndots:0
        search:
        sortlist:
```

**Comment by dawidmalina** [comment]
Let me know when you will be ready for testing - I'm ready to help:)

**Comment by erwindon** [comment]
This is getting confusing...
Can you please (always) provide the output type(nested/yaml/json) and the equivalent JSON data when specifying deviations?

**Comment by dawidmalina** [comment]
Sure. Let me give all 3 types of output:

- value for `dns` grains (default `json` output):
```
{
    "domain": "",
    "ip4_nameservers": [
        "127.0.0.11"
    ],
    "ip6_nameservers": [ ],
    "nameservers": [
        "127.0.0.11"
    ],
    "options": [
        "ndots:0"
    ],
    "search": [ ],
    "sortlist": [ ]
}
```

- value for `dns` grains (`yaml` output):
```
domain: ''
ip4_nameservers:
- 127.0.0.11
ip6_nameservers:
[ ]
nameservers:
- 127.0.0.11
options:
- ndots:0
search:
[ ]
sortlist:
[ ]
```

- value for `dns` grains (`nested` output):
```
domain:
''
ip4_nameservers:
- 127.0.0.11
ip6_nameservers:
[ ]
nameservers:
- 127.0.0.11
options:
- ndots:0
search:
[ ]
sortlist:
[ ]
```

As I mentioned I'm interested in output which will be as close to console output as possible. So I would love to see output like this:
```
----------
domain:
ip4_nameservers:
    - 127.0.0.11
ip6_nameservers:
nameservers:
    - 127.0.0.11
options:
    - ndots:0
search:
sortlist:
```

**Comment by dawidmalina** [comment]
BTW highstate output looks broken:
zrzut ekranu 2019-01-8 o 18 39 35

**Comment by erwindon** [comment]
Thx for the testdata and bugreports. that bug is now fixed.


That value for `ndots` in your earlier example drove me crazy. My (non-docker) system does not report that field, and it looked like a name-value pair. Glad to see that it is actually a confusing string value!


> [...] I'm interested in output which will be as close to console output as possible [...]

I agree (though mostly because that goal prevents any confusion)

**Comment by dawidmalina** [comment]
You can count on me with testing:)

Could you also consider to apply the same (to match console output) for highstate output?
```
----------
          ID: curly
    Function: group.present
      Result: True
     Comment: New group curly created
     Started: 22:21:11.750410
    Duration: 24.483 ms
     Changes:
              ----------
              gid:
                  1002
              members:
              name:
                  curly
              passwd:
                  x
----------
          ID: curly
    Function: user.present
      Result: True
     Comment: New user curly created
     Started: 22:21:11.775613
    Duration: 49.428 ms
     Changes:
              ----------
              fullname:
              gid:
                  1002
              groups:
                  - curly
              home:
                  /home/curly
              homephone:
              name:
                  curly
              other:
              passwd:
                  x
              roomnumber:
              shell:
                  /bin/bash
              uid:
                  1002
              workphone:
----------
          ID: Create a file with contents from an grains
    Function: file.managed
        Name: /tmp/hello
      Result: True
     Comment: File /tmp/hello updated
     Started: 22:21:11.833842
    Duration: 9.205 ms
     Changes:
              ----------
              diff:
                  New file
----------
          ID: python3-dateutil
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 22:45:09.614445
    Duration: 22.495 ms
     Changes:
----------
          ID: python3-django
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: python3-django
     Started: 22:45:09.637445
    Duration: 7681.784 ms
     Changes:
              ----------
              javascript-common:
                  ----------
                  new:
                      11
                  old:
              libjs-jquery:
                  ----------
                  new:
                      3.1.1-2
                  old:
              python-django-common:
                  ----------
                  new:
                      1:1.10.7-2+deb9u3
                  old:
              python3-django:
                  ----------
                  new:
                      1:1.10.7-2+deb9u3
                  old:
              python3-sqlparse:
                  ----------
                  new:
                      0.2.2-1
                  old:
              python3-tz:
                  ----------
                  new:
                      2016.7-0.3
                  old:
```

Where current output looks like this:
```
✔ curly (from users.sls)
    Function is group.present
    New group curly created
    gid: 1002
    name: "curly"
    passwd: "x"
    Started at 22:22:24.945954
    Duration 27 milliseconds
✔ curly (from users.sls)
    Function is user.present
    New user curly created
    fullname: ""
    gid: 1002
    groups: 0: "curly"
    home: "/home/curly"
    homephone: ""
    name: "curly"
    other: ""
    passwd: "x"
    roomnumber: ""
    shell: "/bin/sh"
    uid: 1002
    workphone: ""
    Started at 22:22:24.973214
    Duration 57 milliseconds
✔ /tmp/hello id=Create%20a%20file%20with%20contents%20from%20an%20grains (from files.sls)
    Function is file.managed
    File /tmp/hello updated
    diff: "New file"
    Started at 22:22:25.036119
    Duration 18 milliseconds
✔ python3-dateutil (from python.sls)
    Function is pkg.installed
    All specified packages are already installed
    Started at 22:44:36.678603
    Duration 21 milliseconds
✔ python3-django (from python.sls)
    Function is pkg.installed
    The following packages were installed/updated: python3-django
    javascript-common: "" ► "11"
    libjs-jquery: "" ► "3.2.1-1"
    python-django-common: "" ► "1:1.11.11-1ubuntu1.1"
    python3-django: "" ► "1:1.11.11-1ubuntu1.1"
    python3-sqlparse: "" ► "0.2.4-0.1"
    python3-tz: "" ► "2018.3-2"
    Started at 22:44:36.700519
    Duration 9.751 seconds
```

States used for this test:
- content of `users.sls`
```
curly:
  group:
    - present
  user:
    - present
    - gid_from_name: True
    - require:
      - group: curly
```

- content of `files.sls`
```
Create a file with contents from an grains:
  file.managed:
    - name: /tmp/hello
    - contents: host uuid {{ grains.uuid }}
```

- content of `python`
```
python3-dateutil:
  pkg.installed

python3-django:
  pkg.installed:
    - require:
      - pkg: python3-dateutil
```

**Comment by erwindon** [comment]
re-implemented the NESTED output, this time more closely to the original.
@dawidmalina Can you please verify the NESTED output? yaml output is next (but not today)

**Comment by dawidmalina** [comment]
I've tested and all looks good 👍 and I will create separated ticket for modifying highstate ui: https://github.com/erwindon/SaltGUI/issues/134

**Comment by erwindon** [comment]
@dawidmalina Any objection left on merging this whole branch?

**Comment by dawidmalina** [comment]
No. We can merge it:)

**Pull request merged**
