### PR TITLE
added support for command templates

### PR DESCRIPTION
**Pull request by erwindon**
This PR adds support for templates for the command-box.
As requested in #11.
Templates are maintained in the `master` file.
Values from the selected template are simply copied into the on-screen fields.

### CODE REVIEW

**Comment by erwindon** [comment]
@lostsnow it took a while to honour your request. Some internal plumbing enhancements and some of our own feature requests came first. But now the support for simple templates is there. Do you care to do a functional and/or technical review?

**Comment by lostsnow** [comment]
How about adding a vertical scroll bar when there are too many templates? just add `max-heiget` and `overflow-y` to css.

**Comment by erwindon** [comment]
Seems you are making good use of the templates menu.
I already had scrolling menus in another experimental branch, with the same code as you suggest.
So, just a few minutes please...

**Comment by erwindon** [comment]
The scrolling menu is now there.
Can you please leave a note also when you think no further changes are needed in this area?

**Comment by lostsnow** [comment]
Great, no further changes are needed.

**Pull request merged**
