### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by bsikar**
You should create code analysis.

### CODE REVIEW

**Comment by erwindon** [comment]
@bsikar 
before anything like this is added, please explain how it should be used

**Comment by bsikar** [comment]
So code analysis will allow you to see under the security tab security vulnerabilities in your code. From github: [https://github.com/features/security](https://github.com/features/security). This will allow you to see any possible issues with your code.

For instance, when I added this to my fork, I saw this:
image

Now you are able to dismiss these issues, but it will at least bring them to your attention.

**Comment by erwindon** [comment]
the finding from the screenshot alone is already worth something!
Since this is a github feature, I'll try it out first. Looks like I have to hit some buttons in section "Code security and analysis"...

**Comment by bsikar** [comment]
Yes you will and this file is generated by github, so I can close this pr and you can do it on your end. The file will look exactly the same.

**Comment by erwindon** [comment]
please keep the PR open as it is also a reminder of work at hand

the problem with larger configuration files like this, is that it is unclear whether each of the items in it are just the defaults or not.

**Comment by bsikar** [comment]
Ah I understand, feel free to close it once you get it sorted out, I will keep it open.

**Comment by erwindon** [comment]
fyi: note that the following tools are also regularly use by me:
* npm run stylelint
* npm run eslint

**Comment by erwindon** [comment]
fyi: I just fixed the 2 security warnings:
* the first one was just a coding mistake (see also the above screenprint)
* the second one was a false positive, which I have now suppressed

**Pull request merged**
