### PR TITLE
Enhanced Highstate page

### PR DESCRIPTION
**Pull request by erwindon**
**Is your feature request related to a problem? Please describe.**
I would like a enhanced hightstate page on which we could define some display parameters.

**Describe the solution you'd like**
the enhanced page would allow (at least) selection of the salt-commands to consider for the page :
- with the choice "state.highstate+state.apply" it would have the current functionality
- with the choice "state.highstate" it would be limited to that information only
- with the choice "state.apply" it would be limited to that information only

**Additional context**
we only use "state.highstate" to define whether the server is in highstate or not, and "state.apply" is used only for deployment. So this new page could be very useful. 
see also : https://github.com/erwindon/SaltGUI/issues/458

### CODE REVIEW

**Comment by erwindon** [comment]
migrated _issue_ to _PR_

**Comment by erwindon** [comment]
@pju51 
the "highstate" page now has the option to select for the use of each of state.apply, state.highstate.
the choice is remembered in the browser memory, but outside the session, so that it does not need to be applied again-and-again.
can you please take a look at this?
(I know that your availability in the next weeks is very low, take your time)

**Comment by erwindon** [comment]
@pju51
welcome back!

> still in draft or I can test ?
It is draft because it is still being tested (by you), I'm not currently changing anything. this is mainly a precaution, so that I do not accidentally merge.

same information, different wording:
I updated the "highstate" page.
An option was added to select whether the results from state.apply and/or state.highstate are used to present the data.
This choice is not configurable in the /etc/salt/master file, but it is remembered in the browser that you use.

**Comment by erwindon** [comment]
note that I just rebased again, use "git pull -r" to update

**Comment by pju51** [comment]
Testing..

Highstate page only show the last result ?

Example:
I execute on a server a **state.apply** then a **state.highstate** for X or Y reasons. I can only see the result for **state.highstate** ?

from my side, each day a **state.highstate** (in test mode) is executed to check if we have some server not in highstate, Is it possible to keep this information ? it allows me to monitor my servers and check their status.

**Comment by erwindon** [comment]
> Highstate page only show the last result ?
yes
for each minion, the latest state is shown, but based only on the selected command types, so `state.apply` and/or `state.highstate`, that you select in the panel-settings-menu (the one with the cog). starting with this branch, menu's that have only settings are marked with a cog, other menus still have the hamburger icon.

SaltGUI currently never makes a distinction between regular jobs and jobs with `test=true`. It just does not even look at that parameter.
Should the menu include choices to filter for `"test=true"` and `not("test=true")` on this page?

**Comment by pju51** [comment]
ok so the filter works like a charm.  
not needed to a filter for "test=true" for me.

**Comment by erwindon** [comment]
note: the information from https://pythontechworld.com/issue/saltstack/salt/62410 was helpful to fix my development machine

**Pull request merged**
