### PR TITLE
Add os-amazon icon

### PR DESCRIPTION
**Pull request by dawidmalina**

### CODE REVIEW

**Comment by dawidmalina** [comment]
```
root@saltgui-saltmaster-74fc8cb4b9-99gqd:/# salt \* grains.get os
ip-10-10-12-32.eu-central-1.compute.internal:
    Amazon
ip-10-10-10-123.eu-central-1.compute.internal:
    Amazon
ip-10-10-11-162.eu-central-1.compute.internal:
    Amazon
```

**Comment by erwindon** [comment]
Will merge this after I found out why it was missing and what else is missing too...

**Comment by erwindon** [comment]
OK, found it...
This os-name comes from `/usr/lib/python3.4/site-packages/salt/grains/core.py`, line 1288.
We already support `cloudlinux`, `debian`, `fedora`, `gentoo`, `mint`, `oel`, `redhat`, `scientificlinux` and `suse`.
Unsupported now are: `alt`, `amazon`, `antergos`, `arch-arm`, `arch`, `chapeau`, `kde-neon`, `korora`, `manjaro`, `nilinuxrt`, `nilinuxrt-xfce`, `poky`, `raspbian`, `res`, `synology`, `univention` and `void`.
I'll add some of those too.

**Comment by dawidmalina** [comment]
:+1:

**Pull request merged**
