### PR TITLE
added support for orchestration output

### PR DESCRIPTION
**Pull request by erwindon**
See #268

e.g.:
afbeelding

### CODE REVIEW

**Comment by erwindon** [comment]
@gnouts
I've added a bit of code to recognize the orchestration output and present it in the highstate format.
Can you please try it out in a more real-life situation? thx!

**Comment by erwindon** [comment]
@gnouts
Do you have the opportunity to try it out in a more real-life situation? thx!

**Comment by gnouts** [comment]
Yep I tried this branch with my orchestrators. It works, just like on your screenshot, that's nice :) 
Though I noticed it doesn't honor the state_output settings of the master. So the `ret` was really verbose.

**Comment by erwindon** [comment]
OK, great!

> Though I noticed it doesn't honor the state_output settings of the master.
> So the ret was really verbose.

would you be able to provide an example of that data?
e.g. with `salt-run --out=json state.orchestrate ...`
When you mail it, it will not become visible for others, when that is an issue.

**Comment by erwindon** [comment]
@gnouts 
I accidently skipped your remark about `state_output`.
SaltGUI does not use the variables like `state_verbose` or `state_output`.
But I made a request to support them in #270.

Was the output in your trial-run otherwise ok?
Would you be a able to provide an actual sample output?
(or better, the data behind the output)

**Comment by gnouts** [comment]
@erwindon I'll try to provide you a test example but as I'm doing this in a profesionnal context I might not be able to do it before at least 2 weeks, sorry.
(You might want to merge this one and I'll open an issue as it's not really a major issue.)
Thanks for your work :)

**Comment by erwindon** [comment]
OK!
the merge will happen on the next rainy day (i.e. probably next Saturday)

**Comment by erwindon** [comment]
Sorry for the delay, last Saturday was indeed rainy, but too much other stuff to do...

**Pull request merged**
