### PR TITLE
Introduction of webpack

### PR DESCRIPTION
**Pull request by smarletta**
Hi, 

I have introduced Webpack as bundler. This enables the code to use import/export(ES6 module syntax).

Furthermore it brings the ability to introduce later Typescript, if wanted or needed.

Benefit of ES6 modules: get rid of the unclear dependencies between classes.

Whats coming up from my side:
- the project has bad test coverage(I guess you are not a friend of TDD)
- Util is still on window object which is a bad taste => cmdLineParser was already moved
- some smaller architectural things

If you agree to the webpack usage I will create PRs for all of my upcoming changes.

Dont get me wrong, I love the tool right now. But we would like to use it in an enterprise scale environment.

### CODE REVIEW

**Comment by smarletta** [comment]
Branch with enabled coverage report is available too... will create PR when this one is accepted

**Comment by erwindon** [comment]
Sebastiano,

That is an impressive amount of work!
The main problem with this PR is that it covers multiple areas.
It has:
- rename of files
- changes in yarn framework
- adding coverage tests
- changes in the classes
- changes in js include mechanism
- indentation changes
- ...
There are so many changes that `git diff` is even impractical
So, I will not honour this PR as it is now.

But each of the areas look promising.
I propose that each of the areas is handled separately.
Let's start with the renaming of files in a new PR (and on an actual branch) ?

**Comment by smarletta** [comment]
Well, re-doing everything is a nice amount of work again... Have to think
about how to handle it quite fast.

Erwin Dondorp <notifications@github.com> schrieb am Sa., 2. März 2019,
10:56:

**Comment by dawidmalina** [comment]
@smarletta Wow:) I'm also impressed by number of changes you did. However I agree with @erwindon shape and scope of this pull request is not ok and would be nice if you could split this into small changes. It would be much more simpler to review, discuss and update small parts if needed. Don't take this personal - I know how it is ;)

**Comment by smarletta** [comment]
I don't get you wrong. I totally agree with you two. I just forget to think
about the review.

Will split it up into smaller parts.

Br/sma

Dawid Malinowski <notifications@github.com> schrieb am So., 3. März 2019,
11:36:

**Comment by smarletta** [comment]
Please close PR, will create from scratch with separate PRs for the big topics :-)

**Pull request closed without merging**
