### PR TITLE
Redirect to original URL parameters after login

### PR DESCRIPTION
**Pull request by erwindon**
See issue #431

### CODE REVIEW

**Comment by erwindon** [comment]
@achimmihca
This is the PR for #431
Can you please test this PR?
(at this moment, I cannot assign this one to you, that should be possible after you leave at least one comment here)

**Comment by achimmihca** [comment]
Works great!
Minor issue (only nagging): `reason=no-session` is still in the URI after successful login.
Maybe one could remove this on redirect after successful login.

**Comment by erwindon** [comment]
Thx for testing!

> Minor issue (only nagging): reason=no-session is still in the URI after successful login.

That's not nagging. That is valuable feedback. Fixed that.

Can you test once more: both the original intention and the additional fix?

**Comment by achimmihca** [comment]
Retestet, works like a charm now.
Many thanks!

**Pull request merged**
