### PR TITLE
closing job-details page should redirect to previous page

### PR DESCRIPTION
**Pull request by dawidmalina**
closes: https://github.com/erwindon/SaltGUI/issues/139

### CODE REVIEW

**Comment by dawidmalina** [comment]
Will check this. Any other comments?

**Comment by erwindon** [comment]
no, but please make sure that the implementation is solid. i.e. not a bunch of tweaks until it looks like it is working in all cases...

**Comment by dawidmalina** [comment]
> Go to KEYS page, click first job, click X to close job panel --> see raw api output

can you give me this output (console errors) as I was not able to reproduce this issue

**Comment by erwindon** [comment]
There is no specific console output.
It is just that the url for one of the API calls is in the history. The back-function "returns" to that url.
It seems to be confused about a page url `/jobs`, which is also an API call.

**Comment by dawidmalina** [comment]
Can you describe how I can replicate this?

**Comment by erwindon** [comment]
see above...
Go to KEYS page, click first job, click X to close job panel --> see raw api output (from /keys api call)

**Comment by dawidmalina** [comment]
That's the point. I'm not able to reproduce this. I've event automate this test and play (with ui output) several times without any issues :|

```
    it('valid we can accept minion keys', done => {
      browser
        .type('#username', 'salt')
        .type('#password', 'salt')
        .click('#login-submit')
        .wait( () => {
          // we wait here for the loginpage to be hidden
          const loginpage = document.querySelector('#page_login');
          return loginpage.style.display === 'none';
        })
        .click('#button_keys')
        .wait( () => {
          // we wait here for the loginpage to be shown
          const keyspage = document.querySelector('td div.menu-dropdown-content .run-command-button');
          return keyspage !== null;
        })
        .click("td div.menu-dropdown-content .run-command-button")
        .wait( () => {
          const runcommand = document.querySelector('#run_command');
          return runcommand !== null;
        })
        .click("#run_command")
        .wait( () => {
          const output = document.querySelector("pre.output .host_success");
          return output !== null;
        })
        .end()
        .evaluate( () => { return document.location.href; })
        .then(function (href) {
          assert.equal(href, 'http://localhost:3333/keys');
          done();
        })
        .catch(done);
    });

    it('valid we can run simple job', done => {
      browser
        .type('#username', 'salt')
        .type('#password', 'salt')
        .click('#login-submit')
        .wait( () => {
          // we wait here for the loginpage to be hidden
          const loginpage = document.querySelector('#page_login');
          return loginpage.style.display === 'none';
        })
        .click('#button_manualrun')
        .wait( () => {
          // we wait here for the run_command to be visibale
          const runcommand = document.querySelector('#run_command');
          return runcommand !== null;
        })
        .type('#target', '*')
        .type('#command', 'test.ping')
        .click('#run_command')
        .wait( () => {
          const output = document.querySelector("pre.output .host_success");
          return output !== null;
        })
        .end()
        .evaluate( () => { return document.location.href; })
        .then(function (href) {
          assert.equal(href, url);
          done();
        })
        .catch(done);
    });

    it('valid we can see job details from recent jobs (keys page)', done => {
      browser
        .type('#username', 'salt')
        .type('#password', 'salt')
        .click('#login-submit')
        .wait( () => {
          // we wait here for the loginpage to be hidden
          const loginpage = document.querySelector('#page_login');
          return loginpage.style.display === 'none';
        })
        .click('#button_keys')
        .wait( () => {
          // we wait here for the jobs panel to be shown
          const job = document.querySelector('.jobs td');
          return job !== null;
        })
        .mouseover('.jobs td')
        .click('.jobs td')
        .wait( () => {
          const output = document.querySelector('.job-info h2');
          return output !== null;
        })
        .click('#button_close_job')
        .wait( () => {
          // hack (don't know why .click('#button_close_job') does not work)
          document.querySelector('#button_close_job').click();
          // we wait here for the jobs panel to be shown
          const job = document.querySelector('.jobs td');
          return job !== null;
        })
        .end()
        .evaluate( () => { return document.location.href; })
        .then(function (href) {
          assert.equal(href, 'http://localhost:3333/keys');
          done();
        })
        .catch(done);
    });
```

**Comment by erwindon** [comment]
happens on latest firefox, no extensions active.
also happens on latest chrome, only restlet as extension.

**Comment by erwindon** [comment]
I'm connected to my "real" Salt system on CentOS, so not to the Docker image

**Comment by erwindon** [comment]
The automatic tests use a browser simulation, which may behave differently from an actual browser in these edge cases.

Can you REBASE these changes, so they are more current?

**Comment by dawidmalina** [comment]
BTW - I was able to finally confirm this issue :(

What if we will rename `/jobs` page to `/jobspage` (or similar) and `/keys` page to `keyspage` (or similar) to avoid naming collision as you suggested?

We can go even further and maybe definitely fix the naming collision and introduce uri prefix for example `/p/<current page name>` for regular pages.

**Comment by erwindon** [comment]
> We can go even further and maybe definitely fix the naming collision and introduce uri prefix for example `/p/<current page name>` for regular pages.
great idea (for a separate PR)

**Comment by erwindon** [comment]
I missed the commit that you did just before your latest comment...
Is this PR ready for test (and then merge)?

**Comment by dawidmalina** [comment]
It's working but honestly I would rather redo (validate) this just after https://github.com/erwindon/SaltGUI/issues/182 will be finished.

**Comment by erwindon** [comment]
@dawidmalina 
does it work properly when you rebase this PR?
and can you please revert the whitespace-only change in `login.js`?

**Comment by dawidmalina** [comment]
@erwindon I will work on this pull request. Looks like tests are failing.

**Comment by dawidmalina** [comment]
@erwindon all changes done and looks like all is working properly. Can you please review?

**Comment by erwindon** [comment]
works fine

**Pull request merged**
