### PR TITLE
Add link to project on github on login page

### PR DESCRIPTION
**Pull request by dawidmalina**

### CODE REVIEW

**Comment by erwindon** [comment]
Add `target="_blank"` and I'll merge it...
btw. that will likely be end of the month as I have no free time next week...

**Comment by dawidmalina** [comment]
Target added, please review.

**Comment by erwindon** [comment]
please create a separate PR for a bug fix, so it can be treated with the proper priority

**Comment by dawidmalina** [comment]
Done: https://github.com/erwindon/SaltGUI/pull/146

**Comment by erwindon** [comment]
please rebase to show that all checks succeed...

**Comment by dawidmalina** [comment]
Done

**Comment by erwindon** [comment]
recreated the branch as `github2`, PR #147 
now without the merge from master.
please use REBASE instead next time...

**Pull request closed without merging**
