### PR TITLE
UX grains information as YAML #99

### PR DESCRIPTION
**Pull request by dawidmalina**

### CODE REVIEW

**Comment by erwindon** [comment]
@dawidmalina 
I will not apply this PR as is.
The change is made very specific for the grains/pillar details pages only. It fails to work on the pillar details page and is not active on any other page, which is very asymmetric.
SaltGUI is not a salt command-line simulator.
I did ask you what the purpose of this presentation change was and there was no answer. Can you please provide that answer, preferably in the description of this PR?
I am doubting about the actual purpose. Do you want to SEE data as YAML, or do you want to (RE)USE data as YAML. In the first case I will refuse it anyway since there is no obvious benefit over the existing JSON presentation as it is just a different presentation. In the second case, I would choose for an alternative implementation: Use "View as JSON" and "View as YAML" (or "Copy as JSON" and "Copy as YAML") menu items on each significant piece of data.

**Comment by dawidmalina** [comment]
It's all about yaml which is designed to be readable and editable by humans where json is just a serialization format.

**Comment by erwindon** [comment]
Is `json2yaml.js` your work, or is it re-use?

I'll arrange for presentation in YAML, but not as the default format. I;ll think of a way to switch representations. It will then be used in all pages. i.e. also current job output, historic job output, schedule definition (etc). then also possible to view highstate as json or yaml.

**Comment by dawidmalina** [comment]
It's a fork with some modifications according jslint. Check https://github.com/dawidmalina/json2yaml.

Maybe we could just configure it via master configuration file?

**Comment by erwindon** [comment]
I learnt something today...
The default output from the salt commandline is NOT `--output=yaml`, it is `--output=nested`.
It looks almost the same.

Just checking...
Is your request for NESTED of for YAML?

**Comment by erwindon** [comment]
I was missing the `----------` in the yaml output... :-)

**Comment by dawidmalina** [comment]
Here you go :)
zrzut ekranu 2019-01-5 o 22 16 52

**Comment by erwindon** [comment]
@dawidmalina  I will ignore this pull request and go for my own implementation. That implementation is more generic and supports multiple output formats. I may still use `json2yaml.js` though.
The implementation supports:
* Output is configurable through the `master` file.
* The current (default) configuration is something like `doc,highstate,json`.
* `doc` and `highstate` are only active when the output can be identified as such.
* Other supported outputs are `yaml` and `nested`. But specifying more than one from `[json,yaml,nested]` is useless since these can always be applied.
* syntax colouring is not added.
I'll try to show a working version this week.

**Comment by dawidmalina** [comment]
Ok looks like this topic will be fully covered by https://github.com/erwindon/SaltGUI/pull/133

**Pull request closed without merging**
